channels:
  - pytorch
  - nvidia
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - imageio=2.33.1
  - pytorch==2.4.1
  - torchvision==0.19.1
  - torchaudio==2.4.1
  - pytorch-cuda=12.4
  - scikit-learn=1.5.1
  - scikit-image=0.24.0
  - scipy=1.13.1
  - snakemake=5.27.4
  - numpy=1.26.4
  - tensorboardX=2.6.2.2
  - tqdm=4.66.5
  - pandas=1.5.3
  - pyaml=20.4.0
  - pip>=24.2
  - h5py=3.11.0
  - mrcfile=1.5.3
  - monai=1.4.0